### PR TITLE
remove unnecesary ::: inside SparkR

### PR DESCRIPTION
**Pull request by davies**
I'm not sure about it, all tests passed.

### CODE REVIEW

**Comment by shivaram** [comment]
@davies So we need the `:::` to access package private functions in R. Now we don't need them inside the package itself (i.e. on the driver side). However on the executors we just load the SparkR package like any user would and then run the closures. So its not very clear to me what happens if the closures refer to package private functions. 

@hlin09 Any thoughts on this ?

**Comment by hlin09** [comment]
@shivaram Access to private functions in closure should work well in current implementation of `cleanClosure`. They will be serialized properly, and I think it should be safe to remove `:::`

**Comment by shivaram** [comment]
Thanks @hlin09 for the clarification.

@davies Is the log message cleanup to make the test output better ? The main reason we added the log messages is because we want to tell the user that calling `sparkR.init` twice does not recreate the SparkContext as we cache the java reference.  I think that is still useful to have ?

**Comment by davies** [comment]
@shivaram It makes sense to keeping the logging, because the returned SparkContext object is not in initial state as expected from `sparkR.init`. I will rollback that change.  

Do we still need a logging say `Stopping SparkR`?

**Comment by shivaram** [comment]
Thanks @davies . We probably don't need the `Stopping SparkR` log messages as I think Spark prints a bunch of log messages on SparkContext.stop.

**Comment by shivaram** [comment]
LGTM. Merging this

**Pull request merged**
